require 'rubygems'
require 'bundler/setup'

require File.expand_path('../config/application', __FILE__)

require 'cucumber/rake/task'
require 'guard/rake_task'
require 'rubocop/rake_task'
require 'rspec/core/rake_task'

Rails.application.load_tasks

Guard::RakeTask.new(:guard, '--no-interactions')

Cucumber::Rake::Task.new(:features)
RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

task default: :guard
